### ISSUE TITLE
Routes won't actually appear

### ISSUE THREAD

**Issue by BobJohnson1980** [mspielberg/dv-remote-dispatch#1]
Switches function and do switch the switch in game, but the map is missing the overlay.
(On same network and device, tried mobile same thing happens)

![googleerror](https://user-images.githubusercontent.com/75582780/128779292-58084fa2-164d-4df5-9d4b-0cd06c823ef0.PNG)
![palemoonerror](https://user-images.githubusercontent.com/75582780/128779309-afd0cbf7-1312-46b3-87eb-a0cbb1ebdcf0.PNG)

**Comment by mspielberg** [comment]
What browser are you using? Looks like maybe you clicked a junction before the tracks finished loading?

**Comment by BobJohnson1980** [comment]
Google and pale moon.

**Comment by mspielberg** [comment]
Should be fixed now.
