### ISSUE TITLE
Map rolling stock missing unless operator is nearby.

### ISSUE THREAD

**Issue by tgaguy** [mspielberg/dv-remote-dispatch#23]
Hi. Loving your mod. Use it all the time
IFIK, in previous builds of DV, Remote Dispatch could have rolling stock visibility on the whole map. Now its limited to a range of near where you are. Im assuming this is related to a DV new Build?
Im tring to build a consist with a drop off at another station mid route  but cant see if that track is occupied. i.e. HMB -> SM-B3I drop off -> MB for final destination.

looking from HB
![image](https://github.com/mspielberg/dv-remote-dispatch/assets/29828530/c1fc7769-747f-4c3b-accb-af405aa23fd5)

Teleporting along, this is how close I need to be to see track occupancy. and getting closer, indeed B3I is occupied.
![image](https://github.com/mspielberg/dv-remote-dispatch/assets/29828530/efc1aa87-db35-415a-92a4-be9816cc9d91)

This changed decision making at the start.
Is it possible to see all the wagons on the whole map? that would be awesome,

Thanks,

**Comment by mspielberg** [comment]
Remote Dispatch shows all cars that exist on the map. In vanilla Derail Valley, jobs and their cars are not spawned until the player is near to the station. If the player is not nearby, the jobs and cars despawn automatically, unless they are part of a job that the player has accepted.
